
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwvprveynnckvbendkgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dnBydmV5bm5ja3ZiZW5ka2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTE2NDAsImV4cCI6MjA2MzMyNzY0MH0.UX3ODg1d5IH4AsyUeWRFTbUocYff2UDXcMMNy3BkHhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
